defaults:
  - base 
trainer:
  project_name: coe
  experiment_name: test
  default_local_dir: output
  default_hdfs_dir: null
  total_epochs: null
  total_training_steps: 1000
  validation_interval_steps: 10
  total_validation_count: 100
  logger: ["console", "wandb"]
  eval_only: false  
  
data:
  train_files: data/metamathqa/train.parquet
  val_files: data/metamathqa/test.parquet
  max_length: 512
  truncation: right
  text_keys: ['query', 'response']
  train_batch_size: 256
  micro_batch_size_per_gpu: 64

model:
  partial_pretrain: config/models/coe_deepseekv2
  from_config: true
  override_config:
    _attn_implementation: flash_attention_2
    outer_residual: false
    inner_residual: true
    use_igate: true
    n_shared_experts: 1
    n_routed_experts: 63
    num_experts_per_tok: 8
    inner_iter: 1
    expert_hidden_size: 2048

optim:
  lr_scheduler: constant

general:
  cuda_device: 0
  master_port: 29501

fsdp: true
